# Site settings
title: Devoxx4Kids Polska
email: devoxx4kidspl@gmail.com
description: >
  Devoxx4Kids to wspaniała szansa dla najmłodszych na pierwszy kontakt z programowaniem poprzez zabawę.
  Celem naszego wydarzenia jest pokazanie najmłodszemu pokoleniu, jak sterować i bawić się komputerami. 
  Mamy również nadzieję rozpowszechnić wśród nauczycieli oraz rodziców bogactwo dostępnych za darmo 
  materiałów i narzędzi wspomagających edukację komputerową. Devoxx4Kids Polska to pierwsza, bezpłatna 
  i otwarta konferencja programistyczną dla dzieci będąca częścią światowego ruchu Devoxx4Kids
landing_page_description: "Pierwsza, bezpłatna i otwarta konferencja programistyczną dla dzieci będąca częścią światowego ruchu Devoxx4Kids"
baseurl: ""
url: "http://devoxx4kids.org.pl"
first_published: 2015
social:
  twitter: https://twitter.com/Devoxx4KidsPL
  github: https://github.com/devoxx4kidspl
  facebook: https://www.facebook.com/devoxx4kidspl

# Build settings
markdown: kramdown

collections:
  miasta:
    output: true

exclude:
 - backup